name: AcidicFreedom
main: me.acidorg.AcidicFreedom
version: 1.0
description: Extra Plugin For the TotalFreedom Server
authors: [AcidicCyanide, xXWilee999Xx]
website: totalfreedom.me totalfreedom.boards.net
commands:
  acidicfreedom:
    description: Plugin info.

